apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-stat
  namespace: wordtest
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:                                        # HPA 를 지정할 이름과 스펙을 설정한다.
    apiVersion: apps/v1
    kind: StatefulSet
    name: wp-statefulset
  targetCPUUtilizationPercentage: 70                     # CPU 임계치의 최대값을 설정한다.