apiVersion: v1
kind: Service
metadata:
  name: wp-lb                        # 관리자용 로드벨런서 서비스를 만든다.
spec:                                # 관리자용 인증을 구현하지 않아서 lb 있어도 되고 없어도 된다.
  selector:
    app: mysql
  ports:
  - port: 80
    targetPort: wordpress-port       # 타겟 포트이름을 지정한다.
  type: LoadBalancer