apiVersion: v1
kind: Service
metadata:
  name: sf-hl
spec:
  clusterIP: None              # headless 서비스를 정의하는 코드
  selector:
    app: mysql
  ports:
  - port: 3306 
    targetPort: mysql          # 타겟포트를 이름으로 지정한다.